const models = [
  {
    name: "Report NX Visor Alto",
    description:
      "Nuestra balanza para supermercados Report NX viene preparada para atender todas las exigencias de cualquier negocio. La línea de Balanzas Report de Kretz, te ofrece cada vez más opciones de conexión para mejora las soluciones que tu negocio necesita.",
    image: [
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602500/Kretz-Practica/products/NX%20visor%20alto/huwlslq4atuvw1hndnmw.png",
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602498/Kretz-Practica/products/NX%20visor%20alto/pbe5py5krzcjrdicdt6e.png",
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602498/Kretz-Practica/products/NX%20visor%20alto/aotjdy7m9sef9u4ugk24.png",
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602498/Kretz-Practica/products/NX%20visor%20alto/e8mwvyhn7vmjyctntuao.png",
    ],
    categories: "Balanzas",
    solutions: "Supermercados",
    characteristics: [
      "impresion de ticket, copia de ticket y talon de ticket",
      "50km de vida util de impresion",
      "30kg o 15kg multirango",
      "conexion WIFI, TCP o USB",
    ],
    carrousel: true,
    videos: [],
  },
  {
    name: "Report NX Visor Bajo",
    description:
      "La balanza Report NX se conecta con el software de gestión iTegra de KRETZ para la administración eficiente de tu negocio mediante funcionalidades intuitivas y adaptadas a tus necesidades. iTegra simplifica las operaciones diarias ayudándote a aumentar las ventas, reducir costos y tomar decisiones.",
    image: [
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602499/Kretz-Practica/products/NX%20visor%20bajo/jlpyurw6aekyy7mkpajm.png",
    ],
    categories: "Balanzas",
    solutions: "Supermercados",
    characteristics: [
      "impresion de ticket, copia de ticket y talon de ticket",
      "50km de vida util de impresion",
      "15kg multirango",
      "conexion WIFI o TCP",
    ],
    carrousel: true,
    videos: [],
  },
  {
    name: "Numa NG",
    description:
      "Segunda generación de Cajas Registradoras KRETZ A su facilidad de uso y adaptabilidad a diferentes tipos de negocios se le agrega una nueva tecnología de impresión y de almacenamiento digital brindando una solución a los nuevos requerimientos fiscales.",
    image: [
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602498/Kretz-Practica/products/numa/f4rtch7cyzvrswdonjfb.png",
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602498/Kretz-Practica/products/numa/sh4ngztcll98hpdzk1s9.png",
    ],
    categories: ["Fiscal"],
    solutions: ["Comercios"],
    characteristics: [
      "Cumple con la nueva resolución general 3561/13",
      "10.000 artículos",
      "Memoria fiscal con 3650 Cierres diarios (10 años)",
      "Display operador LCD gráfico",
      "Reportes electrónicos",
      "Impresor TÉRMICO continuo de 57mm de ancho y velocidad de 60 mm/s",
      "Teclado totalmente configurable de 66 teclas",
      "Informes de auditoria impresos",
      "Impresión de código QR",
    ],
    carrousel: true,
    videos: [],
  },
  {
    name: "Report de colgar",
    description:
      "Ideal para ventas de mayoreo y control de procesos. Totalmente construido en acero inoxidable.",
    image: [
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602502/Kretz-Practica/products/report%20de%20colgar/mfedumyl46fg7xs4hsoy.png",
    ],
    categories: ["Balanzas"],
    solutions: ["Supermercados"],
    characteristics: [
      "Trabaja en ambientes humedos",
      "10000 productos, 36 vendedores, Tabla nutricional y recetas",
      "150 Km de impresión",
      "Disponible version Ethernet",
    ],
    carrousel: true,
    videos: [],
  },
  {
    name: "Report LT Visor Bajo",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis similique amet cum ad tempore commodi. Voluptatibus neque voluptatem pariatur consequatur ut labore! Amet quo quasi quae porro aut fugit. Fuga!",
    image: [
      "https://res.cloudinary.com/dpa8t14c2/image/upload/v1722602496/Kretz-Practica/products/LT%20visor%20bajo/bspbbgy6xxecuggdupr9.png",
    ],
    categories: ["Balanzas"],
    solutions: ["Supermercados"],
    characteristics: [
      "Multirango (0 a 15 kg x 5 g) y (15 a 30 kg x 10 g)",
      "Multirango (0 a 6 kg x 2 g) y (6 a 15 kg x 5 g)",
      "Manejo de precio alternativo y precio por rangos.",
      "Conectividad por USB",
      "Hasta 108 teclas de acceso directo.",
      "Impresión de tickets y etiquetas autoadhesivas",
      "Función Pre-empaque. Totalizador de pre empaque",
    ],
    carrousel: true,
    videos: [],
  },
  {
    name: "",
    description: "",
    image: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
    videos: [],
  },
  {
    name: "",
    description: "",
    image: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
    videos: [],
  },
  {
    name: "",
    description: "",
    image: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
    videos: [],
  },
];
