const models = [
  {
    name: "Report NX Visor Alto",
    description: "Nuestra balanza para supermercados Report NX viene preparada para atender todas las exigencias de cualquier negocio. La línea de Balanzas Report de Kretz, te ofrece cada vez más opciones de conexión para mejora las soluciones que tu negocio necesita.",
    images: "https://res.cloudinary.com/dpa8t14c2/image/upload/v1721925262/Kretz-Practica/products/Report%20NX/hbxgismprafp01n3juid.png",
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
  {
    name: "",
    description: "",
    images: [""],
    categories: [""],
    solutions: [""],
    characteristics: [""],
    carrousel: true,
  },
];
