export const distributor = [
  {
    name: "Conecta Patagonia",
    address: "Sarmiento 491",
    Teléfono: "294-4436218",
    Email: "conectapatagoniabche@gmail.com",
    city: "Rio Negro ",
    province: "Bariloche",
    latitude: -41.1382832,
    longitude: -71.2981255,
  },
  {
    name: "Zelian S.A",
    address: "Reservistas Argent 232",
    Teléfono: 1152637676,
    Email: "sin email",
    city: "CABA",
    province: "Buenos Aires",
    latitude:-34.6363204,
    longitude: -58.5242197,
  },
  {
    name: "Kelver Computacion",
    address: "Av. Fondo de la Legua 2949",
    Teléfono: "011-47666890",
    Email: "info@kelver.com.ar",
    city: "Villa Adelina",
    province: "Buenos Aires",
  },
  {
    name: "Coop Ca&ser",
    address: "Moreno 730 - Local 1",
    Teléfono: 1142575657,
    Email: "sin email",
    city: "Quilmes",
    province: "Buenos Aires",
  },
  {
    name: "Casa alsina",
    address: "OLAVARRIA 80",
    Teléfono: "11-50112731",
    Email: "administracion@casaalsina.com.ar",
    city: "Lavallol",
    province: "Buenos Aires",
  },
  {
    name: "Destefano Walter",
    address: "Avenida Aita 785",
    Teléfono: "2317-460636",
    Email: "wdestefano@gmail.com",
    city: "9 de Julio ",
    province: "Buenos Aires",
  },
  {
    name: "Scarpacci Matias",
    address: "PELLEGRINI 1260",
    Teléfono: 3407467986,
    Email: "instalacionesics@yahoo.com.ar",
    city: "Ramallo",
    province: "Buenos Aires",
  },
  {
    name: "Pergamino tecno",
    address: "LARREA 628",
    Teléfono: "2477-558866",
    Email: "sin email",
    city: "Pergamino",
    province: "Buenos Aires",
  },
  {
    name: "Heikele",
    address: "COLECTORA SUR 1040",
    Teléfono: "3489-447231",
    Email: "sin email",
    city: "Zarate/Campana",
    province: "Buenos Aires",
  },
  {
    name: "Vidal Marcelo Roberto",
    address: "AV.TRABAJADORES 2902",
    Teléfono: "2284-699765",
    Email: "info@amoblamientosvidal.com.ar",
    city: "Olavarria",
    province: "Buenos Aires",
  },
  {
    name: "Pineiro",
    address: "HIPOLITO YRIGOYEN  N° 3465",
    Teléfono: 1142975562,
    Email: "sin email",
    city: "Lanus",
    province: "Buenos Aires",
  },
  {
    name: "Leandro Perone",
    address: "Av. CALISTO CALDERON 321",
    Teléfono: "2346-567878",
    Email: "leandro@lprefrigeracion.com.ar",
    city: "Chivilcoy ",
    province: "Buenos Aires",
  },
  {
    name: "Lopresti",
    address: "CALLE 63 Nº 913",
    Teléfono: "2213-648227",
    Email: "sin email",
    city: "La Plata",
    province: "Buenos Aires",
  },
  {
    name: "Belen S.H",
    address: "AV.520 ESQ. 23 - RINQUELET",
    Teléfono: "2214-843006",
    Email: "info@beleninstalaciones.com.ar",
    city: "La Plata",
    province: "Buenos Aires",
  },
  {
    name: "GastroBaires",
    address: " AV. JUJUY 1591",
    Teléfono: "011-49418593",
    Email: "sin email",
    city: "CABA",
    province: "Buenos Aires",
  },
  {
    name: "Matias Delgado ",
    address: "RAWSON 1080",
    Teléfono: " 2254 58-9013",
    Email: "matiasdelgadokretz@gmail.com",
    city: "Villa Gesell//ostende-pinamar",
    province: "Buenos Aires",
  },
  {
    name: "Zonco",
    address: "GRANADEROS 2168",
    Teléfono: "0291-4882828",
    Email: "monicabzonco04@gmail.com.ar",
    city: "Bahia Blanca",
    province: "Buenos Aires",
  },
  {
    name: "Zuntini",
    address: "MITRE   163",
    Teléfono: "0291-4543201",
    Email: "dptocomercial@zuntini.com.ar",
    city: "Bahia Blanca",
    province: "Buenos Aires",
  },
  {
    name: "GASTROQUIL",
    address: "RODOLFO LOPEZ 1550",
    Teléfono: "11-42536707",
    Email: "sin email",
    city: "Quilmes",
    province: "Buenos Aires",
  },
  {
    name: "Cer electronica",
    address: "ASUNCION 1982",
    Teléfono: "011-48361947",
    Email: "cerelectronica@fibertel.com.ar",
    city: "Pilar ",
    province: "Buenos Aires",
  },
  {
    name: "Cosimato",
    address: "BALCARCE 285",
    Teléfono: 2204835233,
    Email: "fabiperezcadelago@hotmail.com",
    city: "Merlo",
    province: "Buenos Aires",
  },
  {
    name: "Cryan ",
    address: "22 1087 PB",
    Teléfono: "2345-463917",
    Email: "Distribuidora25@hotmail.com",
    city: "25 de Mayo",
    province: "Buenos Aires",
  },
  {
    name: "Angeloni ",
    address: "AV.IRIONDO 2544",
    Teléfono: "3498-427534",
    Email: "fernanda@angeloni.com.ar",
    city: "San Justo",
    province: "Buenos Aires",
  },
  {
    name: "Carletti",
    address: "J. BENITEZ 356",
    Teléfono: "336-4663059",
    Email: "sin email",
    city: "San Nicolas",
    province: "Buenos Aires",
  },
  {
    name: "Rag Facturacion",
    address: "Alberti 3875",
    Teléfono: "2235-224457",
    Email: "gerencia.ragfacturacionfiscal@gmail.com",
    city: "Mar Del Plata",
    province: "Buenos Aires",
  },
  {
    name: "Palomo refrigeracion",
    address: "AV.J.PERALTA RAMOS 326",
    Teléfono: "2234-4820536",
    Email: "palomorefrigeracionsrl@hotmail.com",
    city: "Mar Del Plata",
    province: "Buenos Aires",
  },
  {
    name: "Sec Laboratorio",
    address: "San Juan 2557",
    Teléfono: "2234-4930345",
    Email: "sin email",
    city: "Mar Del Plata",
    province: "Buenos Aires",
  },
  {
    name: "INFOMDP S.A",
    address: "20 DE SEPTIEMBRE 2946",
    Teléfono: 2235956367,
    Email: "ventas@infomdp.com.ar",
    city: "Mar Del Plata",
    province: "Buenos Aires",
  },
  {
    name: "Mapa equipamientos",
    address: "MALVINAS ARGENTINAS 509",
    Teléfono: "236-4454060",
    Email: "info@mapaequipamientos.com.ar",
    city: "Junin",
    province: "Buenos Aires",
  },
  {
    name: "Regitronic",
    address: "CARLOS ANTONIO LOPEZ 3620",
    Teléfono: "011-45046869",
    Email: "regitronic@yahoo.com",
    city: "Capital federal",
    province: "Capital federal",
  },
  {
    name: "Click Catamarca",
    address: "AVENIDA BELGRANO 457",
    Teléfono: 383417600,
    Email: "clickcatamarca@gmail.com",
    city: "San Fernando del Valle de Catamarca",
    province: "Catamarca",
  },
  {
    name: "Inforhard",
    address: "SANTA FE 197",
    Teléfono: "0362-4431644",
    Email: "info@inforhard.com.ar",
    city: "Resistencia",
    province: "Chaco",
  },
  {
    name: "AI Servicios ",
    address: "Av Wilde 465",
    Teléfono: "03722-447674",
    Email: "liliana_knyszuk@ai-sa.com.ar",
    city: "Resistencia",
    province: "Chaco",
  },
  {
    name: "Fimel",
    address: "ESPAÑA 1275",
    Teléfono: 2804531622,
    Email: "fimelsrl@speedy.com.ar",
    city: "Chubut",
    province: "Chubut",
  },
  {
    name: "Woodley Jorge",
    address: "JUAN JOSE PASO: PROSPERO PALAZZO 1795",
    Teléfono: "297-4015253",
    Email: "winstalaciones@yahoo.com.ar",
    city: "Comodoro Rivadavia",
    province: "Chubut",
  },
  {
    name: "Pagella Pablo",
    address: "ALEM 451",
    Teléfono: "297-4470621",
    Email: "antomar@speedy.com.ar",
    city: "Comodoro Rivadavia",
    province: "Chubut",
  },
  {
    name: "La Feria Franca",
    address: "SARMIENTO 648",
    Teléfono: "0280-4423993",
    Email: "zonafranca@ventas.com.ar",
    city: "Puerto Madryn",
    province: "Chubut",
  },
  {
    name: "Basiglio ",
    address: "FEDERICO SPHUR 48",
    Teléfono: "02966-431576",
    Email: "ventas@luisbasiglio.com.ar ",
    city: "Puerto Madryn",
    province: "Chubut",
  },
  {
    name: "Quiroga Walter",
    address: "ESPAÑA 1540 ESQ MENDOZA",
    Teléfono: "0280 - 4457597 - 4456599",
    Email: "equiposquirogasur@hotmail.com",
    city: "Puerto Madryn",
    province: "Chubut",
  },
  {
    name: "B y B soluciones",
    address: "TUCUMAN 234",
    Teléfono: "3537-428200//3537-5112",
    Email: "sin email",
    city: "Villa Maria ",
    province: "Cordoba",
  },
  {
    name: "Libra SRL ",
    address: "25 DE MAYO 2711",
    Teléfono: "3564-433700",
    Email: "sin email",
    city: "San Francisco",
    province: "Cordoba",
  },
  {
    name: "Importadora LA",
    address: "OLGA OROZCO 2855",
    Teléfono: "351-4857268",
    Email: "flucero@importadorala.com.ar",
    city: "Barrio Nuevo Poeta Lugones",
    province: "Cordoba",
  },
  {
    name: "Cordoba Tec",
    address: "Nores Martínez 3251 ",
    Teléfono: "351-4265124",
    Email: "sin email",
    city: "barrio jardin",
    province: "Cordoba",
  },
  {
    name: "Nadin ",
    address: "ISABEL LA CATOLICA 784",
    Teléfono: "351-4741375",
    Email: "sin email",
    city: "Cordoba",
    province: "Cordoba",
  },
  {
    name: "Ascona",
    address: "JOSÉ E. GÓMEZ 1435",
    Teléfono: "3777-504068",
    Email: "oascona@goyanet.com.ar",
    city: "Goya ",
    province: "Corrientes",
  },
  {
    name: "GEK",
    address: "HIPOLITO YRIGOYEN 2077",
    Teléfono: 3794400827,
    Email: "mig1alonso@gmail.com",
    city: "Corrientes",
    province: "Corrientes",
  },
  {
    name: "AEME MAQUINAS",
    address: "H.YRIGOYEN 1065",
    Teléfono: "379-4411185",
    Email: "aememaquinassrl@hotmail.com",
    city: "Corrientes",
    province: "Corrientes",
  },
  {
    name: "Micucci",
    address: "ROQUE SAENZ PEÑA 380",
    Teléfono: "0345-422-5157",
    Email: "luismicucci77@gmail.com",
    city: "Concordia",
    province: "Entre Rios",
  },
  {
    name: "Desartec",
    address: "AV. RAMIREZ (casi esq. Pasteur) 3303",
    Teléfono: "343-4079001//3434298869",
    Email: "desartecsrl@gmail.com",
    city: "Parana",
    province: "Entre Rios",
  },
  {
    name: "Centroficina",
    address: "GUALEGUAYCHU 290",
    Teléfono: "343-4231531",
    Email: "sebastian.reula@centroficina.com.ar",
    city: "Parana",
    province: "Entre Rios",
  },
  {
    name: "Marcos Giles",
    address: "9 DE JULIO 1069",
    Teléfono: "3442-422613",
    Email: "agsertec@hotmail.com",
    city: "Concepcion del Uruguay",
    province: "Entre Rios",
  },
  {
    name: "System Formosa",
    address: "AYACUCHO 655",
    Teléfono: "370-4440514",
    Email: "fredy_segovia@yahoo.com.ar",
    city: "Formosa",
    province: "Formosa",
  },
  {
    name: "Soruco",
    address: "SAN MARTIN 1279",
    Teléfono: "0388-4228750",
    Email: "jorge_soruco820@hotmail.com",
    city: "San Salvador de Jujuy",
    province: "Jujuy",
  },
  {
    name: "Junquera Jorge",
    address: "SANTIAGO ALVAREZ 1688",
    Teléfono: "2954-449431",
    Email: "junquera-@hotmail.com",
    city: "Santa Rosa de La Pampa",
    province: "La Pampa",
  },
  {
    name: "Urbizu",
    address: "Av. Argentino Valle esq. Las Heras 643",
    Teléfono: "2954-589618",
    Email: "pablourbizu@cpenet.com.ar",
    city: "Santa Rosa de La Pampa",
    province: "La Pampa",
  },
  {
    name: "Logiciel",
    address: "SALTA 1713",
    Teléfono: "0261-4204433",
    Email: "ddpaez@logicielsrl.com.ar",
    city: "Mendoza",
    province: "Mendoza",
  },
  {
    name: "Contamen",
    address: "Montecaseros 365",
    Teléfono: "0261-4243398//0261-5585061",
    Email: "info@contamen.com.ar",
    city: "Godoy Cruz",
    province: "Mendoza",
  },
  {
    name: "Noziglia",
    address: "FRANCISCO DE HARO 4938",
    Teléfono: 3764420440,
    Email: "equipamientoscom@yahoo.com",
    city: "Posadas",
    province: "Misiones",
  },
  {
    name: "Castillo Walter",
    address: "Jorge Newbery 4184",
    Teléfono: "3764-456262",
    Email: "CASHEREQUIPAMIENTOS@HOTMAIL.COM",
    city: "Misiones",
    province: "Misiones",
  },
  {
    name: "Cañete Leonardo",
    address: "Curruhuinca 779",
    Teléfono: "02972-412200//0294-4820861",
    Email: "lcanete@smandes.com.ar",
    city: "San Martin de los Andes",
    province: "Neuquen",
  },
  {
    name: "Rojas Sebastian",
    address: "12 DE SEPTIEMBRE 895",
    Teléfono: 2994726085,
    Email: "srcfiscales@gmail.com",
    city: "Neuquen",
    province: "Neuquen",
  },
  {
    name: "Regimac ",
    address: "SARMIENTO 37",
    Teléfono: "0299-4774088",
    Email: "regimaqservicios@jetband.com.ar",
    city: "Cipoletti",
    province: "Rio Negro",
  },
  {
    name: "Rotil",
    address: "SAN MARTIN Y MENGELLE",
    Teléfono: "0299-4781881",
    Email: "rotilsrl@gmail.com",
    city: "Cipoletti",
    province: "Rio Negro",
  },
  {
    name: "Del Barco",
    address: "12 DE OCTUBRE 136",
    Teléfono: "387-4313195",
    Email: "matias@delbarcofiscales.com.ar",
    city: "Salta",
    province: "Salta",
  },
  {
    name: "Defazio",
    address: "PUEYRREDON 160 (SUR)",
    Teléfono: "0264-5661117//0264-4274743",
    Email: "servicio_06@hotmail.com",
    city: "San Juan",
    province: "San Juan",
  },
  {
    name: "Pellegrini 143",
    address: "CARLOS PELLEGRINI 143",
    Teléfono: "02664-430998//0266-4455344",
    Email: "sin email",
    city: "San Luis",
    province: "San Luis",
  },
  {
    name: "San Luis Equip",
    address: "maipu 788",
    Teléfono: "0266-154683829 // 0266-4444873/4249694",
    Email: "sin email",
    city: "San Luis",
    province: "San Luis",
  },
  {
    name: "Lemarchand marcos marcelo",
    address: "BERNARDO O HIGGINS 803",
    Teléfono: "2966-216108",
    Email: "mlnexus@hotmail.com",
    city: "Santa Cruz",
    province: "Santa Cruz",
  },
  {
    name: "Sandoval Jorge",
    address: "Pasteur 104 esq. Fagnano",
    Teléfono: "2966-432070 2966-623996",
    Email: "controladoresfiscalesjs@gmail.com",
    city: "Rio Gallegos",
    province: "Santa Cruz",
  },
  {
    name: "Gastro-store",
    address: "Callao 1154",
    Teléfono: "341-4492541",
    Email: "info@e-gastrostore.com",
    city: "Rosario",
    province: "Santa Fe",
  },
  {
    name: "Medina miguel",
    address: "MITRE  1371",
    Teléfono: "3406-440956",
    Email: "sastrecomercial@hotmail.com",
    city: "San Jorge",
    province: "Santa Fe",
  },
  {
    name: "Touma Fernando",
    address: "ROCA 278",
    Teléfono: "3462-431099//3462-467611",
    Email: "toumacomercial@powervt.com.ar",
    city: "Venado Tuerto",
    province: "Santa Fe",
  },
  {
    name: "Petenatti",
    address: "SAN MARTIN 898",
    Teléfono: "3462-470600",
    Email: "tesoreria@petenattihnos.com.ar",
    city: "Firmat",
    province: "Santa Fe",
  },
  {
    name: "Baras Walter",
    address: "GOROSTIAGA 2039",
    Teléfono: "342-4608581",
    Email: "walterbaras@ciudad.com.ar",
    city: "Santa Fe",
    province: "Santa Fe",
  },
  {
    name: "Patrone equipamientos",
    address: "SAN MARTIN 6047",
    Teléfono: "342-4604588",
    Email: "patroneequipamientos@gmail.com",
    city: "Santa Fe",
    province: "Santa Fe",
  },
  {
    name: "AECO ",
    address: "Remedios de Escalada 402",
    Teléfono: "3492-430871",
    Email: "electrodomesticos@aecorafaela.com.ar",
    city: "Rafaela",
    province: "Santa Fe",
  },
  {
    name: "Garbe Daniel",
    address: "AV.CORDOBA 2011",
    Teléfono: "3490-421582",
    Email: "ventas@dlgarbe.com.ar",
    city: "Esperanza",
    province: "Santa Fe",
  },
  {
    name: "Nardelli Luis",
    address: "BME.MITRE 1101",
    Teléfono: "3482-420435",
    Email: "compras@nardellihnos.com.ar",
    city: "Reconquista ",
    province: "Santa Fe",
  },
  {
    name: "Ofi Maq",
    address: "SAN MARTIN 2591",
    Teléfono: "3476-422690",
    Email: "ofimaqsl@gmail.com",
    city: "San Lorenzo",
    province: "Santa Fe",
  },
  {
    name: "Balanmac",
    address: "PASCO 1236",
    Teléfono: "341-6626808",
    Email: "ventas@balanmac.com",
    city: "Rosario",
    province: "Santa Fe",
  },
  {
    name: "Molinari Fiscales",
    address: "CORRIENTES 1577",
    Teléfono: "341-4403411",
    Email: "molinari-point@hotmail.com",
    city: "Rosario",
    province: "Santa Fe",
  },
  {
    name: "Frio San ",
    address: "CATAMARCA 2599",
    Teléfono: "341-4598556",
    Email: "contacto@frio-san.com.ar",
    city: "Rosario",
    province: "Santa Fe",
  },
  {
    name: "Gonzales Carlos",
    address: "PJE PITAGORAS (JUNIN 7400)",
    Teléfono: "341-5021390",
    Email: "CAGONZALEZPAN@GMAIL.COM",
    city: "Rosario",
    province: "Santa Fe",
  },
  {
    name: "Di Benedetto Analia",
    address: "HIPOLITO YRIGOYEN 1346",
    Teléfono: "3464 440059",
    Email: "dyaservicios@gmail.com",
    city: "Casilda",
    province: "Santa Fe",
  },
  {
    name: "Nusbaum",
    address: "PERU 1240",
    Teléfono: 3854222795,
    Email: "raulnusbaum@gmail.com",
    city: "Santiago del Estero",
    province: "Santiago del Estero",
  },
  {
    name: "Messina ",
    address: "LA RIOJA 15",
    Teléfono: "381-4214620",
    Email: "messina.mys@gmail.com",
    city: "San Miguel de Tucuman",
    province: "Tucuman",
  },
];
